/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Files;
import controlador.GetFromURL;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import org.json.simple.parser.ParseException;
import modelo.Card;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JComboBox;
import javax.swing.JMenuItem;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.BoxLayout;
import javax.swing.SwingConstants;
import java.awt.Component;
import java.awt.Dimension;

/**
 *
 * @author Jorge
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }
    Files fl = new Files();
    GetFromURL fromURL = new GetFromURL();
    static String selectedCard = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel2.setAlignmentY(Component.TOP_ALIGNMENT);
        jPanel2.setAlignmentX(Component.LEFT_ALIGNMENT);
        jButtonAdd = new javax.swing.JButton();
        jButtonAdd.setEnabled(false);
        jButtonNew = new javax.swing.JButton();
        jButtonNew.setAlignmentX(Component.CENTER_ALIGNMENT);
        jButtonNew.setEnabled(false);
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSave = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonDelete.setEnabled(false);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        GridBagLayout gbl_jPanel2 = new GridBagLayout();
        gbl_jPanel2.columnWidths = new int[] {100, 245};
        gbl_jPanel2.rowHeights = new int[] {20, 20, 20, 20, 21, 96, 20, 20};
        gbl_jPanel2.columnWeights = new double[]{0.0, 0.0};
        gbl_jPanel2.rowWeights = new double[]{0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0};
        jPanel2.setLayout(gbl_jPanel2);
        jTextFldEngName = new javax.swing.JTextField();
        jTextFldEngName.setHorizontalAlignment(SwingConstants.LEFT);
        jTextFldEngName.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyPressed(KeyEvent e) {
        		jTextFldEngName.setBackground(Color.white);;
        	}
        });
                jLabelEngName = new javax.swing.JLabel();
                
                        jLabelEngName.setText("Nombre (ENG):");
                        GridBagConstraints gbc_jLabelEngName = new GridBagConstraints();
                        gbc_jLabelEngName.anchor = GridBagConstraints.WEST;
                        gbc_jLabelEngName.insets = new Insets(0, 0, 5, 5);
                        gbc_jLabelEngName.gridx = 0;
                        gbc_jLabelEngName.gridy = 0;
                        jPanel2.add(jLabelEngName, gbc_jLabelEngName);
        
                jTextFldEngName.setText("Eng name");
                GridBagConstraints gbc_jTextFldEngName = new GridBagConstraints();
                gbc_jTextFldEngName.fill = GridBagConstraints.HORIZONTAL;
                gbc_jTextFldEngName.insets = new Insets(0, 0, 5, 0);
                gbc_jTextFldEngName.gridx = 1;
                gbc_jTextFldEngName.gridy = 0;
                jPanel2.add(jTextFldEngName, gbc_jTextFldEngName);
        jLabelSpaName = new javax.swing.JLabel();
        
                jLabelSpaName.setText("Nombre (SPA):");
                GridBagConstraints gbc_jLabelSpaName = new GridBagConstraints();
                gbc_jLabelSpaName.anchor = GridBagConstraints.WEST;
                gbc_jLabelSpaName.insets = new Insets(0, 0, 5, 5);
                gbc_jLabelSpaName.gridx = 0;
                gbc_jLabelSpaName.gridy = 1;
                jPanel2.add(jLabelSpaName, gbc_jLabelSpaName);
        jTextFldSpaName = new javax.swing.JTextField();
        jTextFldSpaName.setHorizontalAlignment(SwingConstants.LEFT);
        jTextFldSpaName.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyPressed(KeyEvent e) {
        		jTextFldSpaName.setBackground(Color.white);
        	}
        });
        
                jTextFldSpaName.setText("Spa name");
                GridBagConstraints gbc_jTextFldSpaName = new GridBagConstraints();
                gbc_jTextFldSpaName.fill = GridBagConstraints.HORIZONTAL;
                gbc_jTextFldSpaName.insets = new Insets(0, 0, 5, 0);
                gbc_jTextFldSpaName.gridx = 1;
                gbc_jTextFldSpaName.gridy = 1;
                jPanel2.add(jTextFldSpaName, gbc_jTextFldSpaName);
        jLabelAttrib = new javax.swing.JLabel();
        
                jLabelAttrib.setText("Atributo:");
                GridBagConstraints gbc_jLabelAttrib = new GridBagConstraints();
                gbc_jLabelAttrib.anchor = GridBagConstraints.WEST;
                gbc_jLabelAttrib.insets = new Insets(0, 0, 5, 5);
                gbc_jLabelAttrib.gridx = 0;
                gbc_jLabelAttrib.gridy = 2;
                jPanel2.add(jLabelAttrib, gbc_jLabelAttrib);
        GridBagConstraints gbc_panel = new GridBagConstraints();
        gbc_panel.fill = GridBagConstraints.HORIZONTAL;
        gbc_panel.insets = new Insets(0, 0, 5, 0);
        gbc_panel.gridx = 1;
        gbc_panel.gridy = 2;
        jPanel2.add(panel, gbc_panel);
        panel.setLayout(new BoxLayout(panel, BoxLayout.X_AXIS));
        jComboBoxAttrib = new javax.swing.JComboBox<>();
        panel.add(jComboBoxAttrib);
        
                jComboBoxAttrib.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","AGUA", "DIVINIDAD", "FUEGO", "LUZ", "OSCURIDAD", "TIERRA", 
                		"VIENTO", "MÁGICA", "TRAMPA" }));
                jButton1 = new javax.swing.JButton();
                jButton1.setMinimumSize(new Dimension(50, 9));
                panel.add(jButton1);
                
                        jButton1.setText("Obtener Datos");
                        jButton1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                            }
                        });
                jComboBoxAttrib.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jComboBoxAttribEvent(evt);
                    }
                });
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea1.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyPressed(KeyEvent e) {
        		jTextArea1.setBackground(Color.white);;
        	}
        });
        
                jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
                jScrollPane1.setMinimumSize(new java.awt.Dimension(166, 96));
                
                        jTextArea1.setColumns(20);
                        jTextArea1.setLineWrap(true);
                        jTextArea1.setRows(10);
                        jTextArea1.setWrapStyleWord(true);
                        jTextArea1.setMaximumSize(new java.awt.Dimension(200, 200));
                        jTextArea1.setMinimumSize(new java.awt.Dimension(50, 50));
                        jTextArea1.setName(""); // NOI18N
                        jLabelLevel = new javax.swing.JLabel();
                        
                                jLabelLevel.setText("Nivel/LINK:");
                                GridBagConstraints gbc_jLabelLevel = new GridBagConstraints();
                                gbc_jLabelLevel.anchor = GridBagConstraints.WEST;
                                gbc_jLabelLevel.insets = new Insets(0, 0, 5, 5);
                                gbc_jLabelLevel.gridx = 0;
                                gbc_jLabelLevel.gridy = 3;
                                jPanel2.add(jLabelLevel, gbc_jLabelLevel);
                        jComboBoxLvl = new javax.swing.JComboBox<>();
                        
                                jComboBoxLvl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
                                GridBagConstraints gbc_jComboBoxLvl = new GridBagConstraints();
                                gbc_jComboBoxLvl.fill = GridBagConstraints.HORIZONTAL;
                                gbc_jComboBoxLvl.insets = new Insets(0, 0, 5, 0);
                                gbc_jComboBoxLvl.gridx = 1;
                                gbc_jComboBoxLvl.gridy = 3;
                                jPanel2.add(jComboBoxLvl, gbc_jComboBoxLvl);
                        jLabelType = new javax.swing.JLabel();
                        
                                jLabelType.setText("Tipo(s):");
                                GridBagConstraints gbc_jLabelType = new GridBagConstraints();
                                gbc_jLabelType.anchor = GridBagConstraints.WEST;
                                gbc_jLabelType.insets = new Insets(0, 0, 5, 5);
                                gbc_jLabelType.gridx = 0;
                                gbc_jLabelType.gridy = 4;
                                jPanel2.add(jLabelType, gbc_jLabelType);
                        jPanelTypes = new javax.swing.JPanel();
                        jComboBox1 = new javax.swing.JComboBox<>();
                        
                                jPanelTypes.setLayout(new javax.swing.BoxLayout(jPanelTypes, javax.swing.BoxLayout.LINE_AXIS));
                                
                                        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","Aqua", "Bestia", "Bestia Alada", "Ciberso", "Demonio", "Dinosaurio", 
                                        		"Dragón", "Guerrero", "Guerrero-Bestia", "Hada", "Insecto", "Lanzador de Conjuros", "Máquina", "Pez", "Planta", "Psíquico", "Piro", 
                                        		"Reptil", "Roca", "Serpiente Marina", "Trueno", "Wyrm", "Zombi" }));
                                        jPanelTypes.add(jComboBox1);
                                        GridBagConstraints gbc_jPanelTypes = new GridBagConstraints();
                                        gbc_jPanelTypes.anchor = GridBagConstraints.NORTH;
                                        gbc_jPanelTypes.fill = GridBagConstraints.HORIZONTAL;
                                        gbc_jPanelTypes.insets = new Insets(0, 0, 5, 0);
                                        gbc_jPanelTypes.gridx = 1;
                                        gbc_jPanelTypes.gridy = 4;
                                        jPanel2.add(jPanelTypes, gbc_jPanelTypes);
                        jLabelText = new javax.swing.JLabel();
                        
                                jLabelText.setText("Texto:");
                                GridBagConstraints gbc_jLabelText = new GridBagConstraints();
                                gbc_jLabelText.anchor = GridBagConstraints.WEST;
                                gbc_jLabelText.insets = new Insets(0, 0, 5, 5);
                                gbc_jLabelText.gridx = 0;
                                gbc_jLabelText.gridy = 5;
                                jPanel2.add(jLabelText, gbc_jLabelText);
                        jScrollPane1.setViewportView(jTextArea1);
                        GridBagConstraints gbc_jScrollPane1 = new GridBagConstraints();
                        gbc_jScrollPane1.fill = GridBagConstraints.BOTH;
                        gbc_jScrollPane1.insets = new Insets(0, 0, 5, 0);
                        gbc_jScrollPane1.gridx = 1;
                        gbc_jScrollPane1.gridy = 5;
                        jPanel2.add(jScrollPane1, gbc_jScrollPane1);
        jLabelATK = new javax.swing.JLabel();
        
                jLabelATK.setText("ATK:");
                GridBagConstraints gbc_jLabelATK = new GridBagConstraints();
                gbc_jLabelATK.anchor = GridBagConstraints.WEST;
                gbc_jLabelATK.insets = new Insets(0, 0, 5, 5);
                gbc_jLabelATK.gridx = 0;
                gbc_jLabelATK.gridy = 6;
                jPanel2.add(jLabelATK, gbc_jLabelATK);
        jTextFldATK = new javax.swing.JTextField();
        
                jTextFldATK.setText("0");
                GridBagConstraints gbc_jTextFldATK = new GridBagConstraints();
                gbc_jTextFldATK.fill = GridBagConstraints.HORIZONTAL;
                gbc_jTextFldATK.insets = new Insets(0, 0, 5, 0);
                gbc_jTextFldATK.gridx = 1;
                gbc_jTextFldATK.gridy = 6;
                jPanel2.add(jTextFldATK, gbc_jTextFldATK);
        jLabelDEF = new javax.swing.JLabel();
        
                jLabelDEF.setText("DEF:");
                GridBagConstraints gbc_jLabelDEF = new GridBagConstraints();
                gbc_jLabelDEF.anchor = GridBagConstraints.WEST;
                gbc_jLabelDEF.insets = new Insets(0, 0, 0, 5);
                gbc_jLabelDEF.gridx = 0;
                gbc_jLabelDEF.gridy = 7;
                jPanel2.add(jLabelDEF, gbc_jLabelDEF);
        jTextFldDEF = new javax.swing.JTextField();
        
                jTextFldDEF.setText("0");
                GridBagConstraints gbc_jTextFldDEF = new GridBagConstraints();
                gbc_jTextFldDEF.fill = GridBagConstraints.HORIZONTAL;
                gbc_jTextFldDEF.gridx = 1;
                gbc_jTextFldDEF.gridy = 7;
                jPanel2.add(jTextFldDEF, gbc_jTextFldDEF);

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonNew.setText("New");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Cartas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButtonSave.setText("Save");
        jButtonSave.setEnabled(false);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(255, 102, 102));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDelete.setText("X");
        jButtonDelete.setAlignmentY(0.0F);
        jButtonDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonDelete.setBorderPainted(false);
        jButtonDelete.setContentAreaFilled(false);
        jButtonDelete.setOpaque(true);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jMenu1.setText("Config");
        jMenu1.setActionCommand("Ruta");

        jMenuItem1.setText("Cargar Base");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        
        jMenuItemNew = new JMenuItem("New Base");
        jMenuItemNew.addActionListener(new ActionListener() {
        	public void actionPerformed(java.awt.event.ActionEvent evt) {
        		jMenuNewAction(evt);
        	}
        });
        jMenu1.add(jMenuItemNew);
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(10)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 346, GroupLayout.PREFERRED_SIZE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(55)
        					.addComponent(jButtonAdd)
        					.addGap(42)
        					.addComponent(jButtonSave)
        					.addGap(40)
        					.addComponent(jButtonNew)
        					.addGap(18)
        					.addComponent(jButtonDelete, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)))
        			.addGap(3)
        			.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 241, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 400, GroupLayout.PREFERRED_SIZE)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jButtonAdd)
        						.addComponent(jButtonSave)
        						.addComponent(jButtonNew)
        						.addComponent(jButtonDelete))))
        			.addContainerGap())
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jComboBoxAttribEvent(java.awt.event.ActionEvent evt) {
    	if (jComboBoxAttrib.getSelectedIndex()==8 || jComboBoxAttrib.getSelectedIndex()==9) {
    		jTextFldATK.setText("0");
			jTextFldDEF.setText("0");
			jComboBoxLvl.setSelectedIndex(1);
			this.desactivar(new Object[] {jTextFldATK,jTextFldDEF,jComboBox1,jComboBoxLvl},false);
		} else {
			this.desactivar(new Object[] {jTextFldATK,jTextFldDEF,jComboBox1,jComboBoxLvl},true);
		}
    }

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
    	Object[] auxJObjects = {jTextFldEngName,jTextFldSpaName, jComboBoxAttrib, jComboBoxLvl, jComboBox1, jTextArea1, jTextFldATK, jTextFldDEF};
    	switch (jComboBoxAttrib.getSelectedItem().toString()) {
		case "MÁGICA":
			auxJObjects[3]=0;
			auxJObjects[4]=0;
			auxJObjects[6]=0;
			auxJObjects[7]=0;
			break;
		
		case "TRAMPA":
			auxJObjects[3]=0;
			auxJObjects[4]=0;
			auxJObjects[6]=0;
			auxJObjects[7]=0;
			break;

		default:
			break;
		}
    	
    	int aux = 0;
    	for (Object object : auxJObjects) {
			aux += fl.verificarCampo(object);
		}
    	if(aux == 0) {
    		if (!fl.verificarSiExiste(jTextFldSpaName.getText())) {
    			fl.addCard(jTextFldSpaName.getText(), jTextFldEngName.getText(), 
    		    jComboBoxAttrib.getSelectedItem().toString(), jComboBox1.getSelectedItem().toString(), 
    		    jTextArea1.getText(), Integer.parseInt((String)jComboBoxLvl.getSelectedItem()),
    		    Integer.parseInt(jTextFldATK.getText().toString()), Integer.parseInt(jTextFldDEF.getText().toString()));
    		    try {
    				jTable1.setModel(fl.loadJsonToTable());
    				jButtonAdd.setEnabled(false);
    			} catch (NullPointerException | IOException | ParseException e) {
    				// TODO Auto-generated catch block
    				e.printStackTrace();
    			}
			} else {
				JOptionPane.showMessageDialog(this, "La carta ya esta registrada");
			}
    	}else {
			JOptionPane.showMessageDialog(this, "Llene todos los campos");
		}
       
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    	fl.loadChooser(this);
        try {
			jTable1.setModel(fl.loadJsonToTable());
			jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
	        this.setTitle(fl.getRuta());
	        this.jButtonAdd.setEnabled(true);
	        jButtonNew.setEnabled(true);
            jButton1.setEnabled(true);
		} catch (NullPointerException | IOException | ParseException e) {
			JOptionPane.showMessageDialog(rootPane, "LOL 2 error", "Error", JOptionPane.ERROR_MESSAGE);
			e.printStackTrace();
		}
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void jMenuNewAction(ActionEvent evt) {
    	fl.saveChooser(this);
		try {
			fl.loadJsonToTable();
			this.setTitle(fl.getRuta());
		} catch (NullPointerException | IOException | ParseException e1) {
			JOptionPane.showMessageDialog(rootPane, "LOL 1 error", "Error", JOptionPane.ERROR_MESSAGE);
			e1.printStackTrace();
		}
		this.setTitle(fl.getRuta());
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            int row = jTable1.getSelectedRow();
            Card auxCarf = fl.getSelectedCard(row);
            jTextFldSpaName.setText(auxCarf.getSpaName());
            jTextFldEngName.setText(auxCarf.getEngName());
            jComboBoxAttrib.setSelectedItem(auxCarf.getAttribute());
            jComboBoxLvl.setSelectedItem(auxCarf.getLevel()+"");
            jComboBox1.setSelectedItem(auxCarf.getType());
            jTextArea1.setText(auxCarf.getText());
            jTextFldATK.setText(auxCarf.getAttak()+"");
            jTextFldDEF.setText(auxCarf.getDefense()+"");
            this.desactivar(new Object[] {jButtonAdd,jButton1}, false);
            this.desactivar(new Object[] {jButtonSave,jButtonDelete,jComboBoxAttrib}, true);
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        jTextFldSpaName.setText("");
        jTextFldEngName.setText("");
        jTextArea1.setText("");
        jTextFldATK.setText("");
        jTextFldDEF.setText("");
        this.desactivar(new Object[] {jButtonSave,jButtonDelete}, false);
        this.desactivar(new Object[] {jButtonAdd,jButton1,jComboBox1,jComboBoxAttrib,jComboBoxLvl,jTextArea1,jTextFldATK,jTextFldDEF}, true);
        jComboBox1.setSelectedIndex(0);
        jComboBoxAttrib.setSelectedIndex(0);
        jComboBoxLvl.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        fl.deleteCrd(jTable1.getSelectedRow());
        try {
			jTable1.setModel(fl.loadJsonToTable());
		} catch (NullPointerException | IOException | ParseException e) {
			JOptionPane.showMessageDialog(rootPane, "LOL 3 error", "Error", JOptionPane.ERROR_MESSAGE);
			e.printStackTrace();
		}
        jButtonNewActionPerformed(evt);
    }//GEN-LAST:event_jButtonDeleteActionPerformed

//    private void jTextFldSpaNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFldSpaNameMouseClicked
//    	Object[] auxJObjects = {jTextFldEngName};
//    	int error = 0;
//    	for (Object object : auxJObjects) {
//			error += fl.verificarCampo(object);
//		}
//        if (evt.getClickCount() == 3 && !evt.isConsumed()) {
//            evt.consume();
//            foo();
//			}
//        }
//    }//GEN-LAST:event_jTextFldSpaNameMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	Object[] auxJObjects = {jTextFldEngName};
    	int error = 0;
    	for (Object object : auxJObjects) {
			error += fl.verificarCampo(object);
		}
    	if (error == 0) {
    		try {
                ArrayList<String> aux = fromURL.getAttrib(fromURL.getSpanishName(jTextFldEngName.getText()));
                jTextFldSpaName.setText(aux.get(0).toString());
                jComboBoxAttrib.setSelectedItem(aux.get(3));
                jComboBoxLvl.setSelectedItem(aux.get(4).toString());
                jComboBox1.setSelectedItem(aux.get(5));
                jTextFldATK.setText(aux.get(6).toString());
				jTextFldDEF.setText(aux.get(7).toString());
                jTextArea1.setText(fromURL.textFromURL(jTextFldSpaName.getText()));
                this.desactivar(new Object[]{jComboBox1,jComboBoxAttrib,jComboBoxLvl,jTextArea1,jTextFldATK,jButton1,jTextFldDEF},false);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "La carta no existe, revise el nombre");
            }
		} else {
			JOptionPane.showMessageDialog(rootPane, "Campo vacio, no hay nombre de carta");
			jTextFldSpaName.setBackground(Color.cyan);
		}
    	
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /*t
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    private void desactivar(Object jCampos[],boolean enabled) {
    	for (Object object : jCampos) {
    		switch (object.getClass().toString()) {
    		case "class javax.swing.JTextArea":
    			((JTextArea)object).setEditable(enabled);
    			break;
    		
    		case "class javax.swing.JTextField":
    			((JTextField)object).setEditable(enabled);
    			break;
    			
    		case "class javax.swing.JComboBox":
    			((JComboBox)object).setEnabled(enabled);
    			break;
    			
    		case "class javax.swing.JButton":
    			((JButton)object).setEnabled(enabled);
    			break;
    			
    		default:
    			break;
    		}
		}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxAttrib;
    private javax.swing.JComboBox<String> jComboBoxLvl;
    private javax.swing.JLabel jLabelATK;
    private javax.swing.JLabel jLabelAttrib;
    private javax.swing.JLabel jLabelDEF;
    private javax.swing.JLabel jLabelEngName;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelSpaName;
    private javax.swing.JLabel jLabelText;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelTypes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFldATK;
    private javax.swing.JTextField jTextFldDEF;
    private javax.swing.JTextField jTextFldEngName;
    private javax.swing.JTextField jTextFldSpaName;
    private JMenuItem jMenuItemNew;
    private final JPanel panel = new JPanel();
}
